a = input('Digite algo:')
print('Qual o tipo da variavel?', type(a))
print('É alpha numerico?', a.isalnum())
print('É alpha?', a.isalpha())
print('É numerico?', a.isnumeric())
print('É decimal?', a.isdecimal())
print('Tem somente espaço? ', a.isspace())
print('Está em maiuscula?', a.isupper())
print('Está em minúcula?', a.islower())
