n1 = int(input('Digite um numero: '))
n2 = int(input('Digite outro numero: '))
soma = int((n1 + n2))
# print('A soma entre {}'.format(n1), 'e {}'.format(n2), 'resulta em {}'.format(soma) )
print('A soma entre {} e {} resulta em {}'.format(n1, n2, soma))
